# Generated by Django 4.0.2 on 2022-07-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookorm',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderorm',
            name='choose_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderorm',
            name='purchased_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderorm',
            name='status',
            field=models.CharField(choices=[('choose', 'Choose'), ('purchased', 'Purchased')], default='choose', max_length=20),
        ),
        migrations.AddField(
            model_name='orderorm',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
